# Generated by Django 5.0.3 on 2024-03-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.BooleanField(choices=[('property_owner', 'Property Owner'), ('buyer', 'Buyer')], null=True),
        ),
    ]
